name: Build and Test

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build API
        run: npm run build --workspace=api
      
      - name: Build Frontend
        run: npm run build --workspace=frontend
      
      - name: Run API tests
        run: npm run test --workspace=api
      
      - name: Lint code
        run: npm run lint --workspace=frontend
      
      - name: Build API Docker image (without push)
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: false
          tags: octocat-api:latest
      
      - name: Build Frontend Docker image (without push)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          tags: octocat-frontend:latest
